### ISSUE TITLE
Stuck moving left or right

### ISSUE THREAD

**Issue by ZT-1** [geeky/dinput8wrapper#2]
At random times, you can get stuck continuously moving left or right without touching anything until you pause and unpause the game.

**Comment by geeky** [comment]
I can reproduce the error and can probably fix this. An update might become available next sunday

**Comment by geeky** [comment]
Just released https://github.com/geeky/dinput8wrapper/releases/tag/v1.0.0.2 which hopefuly solves this issue

**Comment by ZT-1** [comment]
Seems to be fixed now, thanks.
